BaseURL: "http://cogneco.com/"
languageCode: "en-US"
title: "Cogneco"
MetaDataFormat: "toml"
blackfriday:
  extensions:
    - hardLineBreak
theme: hugo-theme-html5
params:
  Logotype: "img/cogneco-h2w.svg"
  CSS:
    - "css/text.css"
    - "css/color.css"
    - "css/layout.css"
    - "css/form.css"
  ListMode: "full"
  FrontPageMode: "full"
  FrontPageSection: "index"
  NavigationInHeader: true
